import { Injectable } from '@nestjs/common';
import {
  type InvoiceDto,
  type InvoiceLineItemDto,
  type InvoiceStatus,
  type InvoiceTaxDto,
  type InvoiceType,
  type PaymentDto,
  type PaymentMethod,
  invoiceStatusLabel,
  invoiceTypeLabel,
  paymentMethodLabel,
} from '@ustowdispatch/shared';
/**
 * InvoicePdfService — renders a customer-facing invoice PDF using PDFKit.
 *
 * Decision (commit message has the rationale): PDFKit over @react-pdf/renderer.
 * Smaller dependency tree, simpler imperative API, no JSX runtime. The PDF
 * renders to bytes; persistence to the StorageProvider happens in
 * InvoicesService.streamPdf() — keeps PDF rendering free of storage concerns.
 *
 * Bilingual (EN / ES): each label string switches on the `language` param.
 */
import PDFDocument from 'pdfkit';

export type PdfLanguage = 'en' | 'es';

const LABELS_EN = {
  invoice: 'INVOICE',
  receipt: 'RECEIPT',
  invoice_number: 'Invoice #',
  invoice_date: 'Invoice date',
  due_date: 'Due date',
  paid_date: 'Paid on',
  void_date: 'Voided on',
  bill_to: 'Bill to',
  ship_from: 'From',
  status: 'Status',
  description: 'Description',
  qty: 'Qty',
  unit_price: 'Unit price',
  line_total: 'Amount',
  subtotal: 'Subtotal',
  tax: 'Tax',
  total: 'Total',
  paid: 'Paid',
  balance: 'Balance due',
  thank_you: 'Thank you for your business.',
  payments: 'Payments',
  no_payments: 'No payments recorded.',
  payment_date: 'Date',
  payment_method: 'Method',
  payment_amount: 'Amount',
  payment_reference: 'Reference',
  notes: 'Notes',
  generated_by: 'Generated by US Tow DISPATCH',
  terms: 'Terms',
};

const LABELS_ES = {
  invoice: 'FACTURA',
  receipt: 'RECIBO',
  invoice_number: 'Factura #',
  invoice_date: 'Fecha de emisión',
  due_date: 'Fecha de vencimiento',
  paid_date: 'Pagado el',
  void_date: 'Anulado el',
  bill_to: 'Facturar a',
  ship_from: 'De',
  status: 'Estado',
  description: 'Descripción',
  qty: 'Cant.',
  unit_price: 'Precio unitario',
  line_total: 'Importe',
  subtotal: 'Subtotal',
  tax: 'Impuesto',
  total: 'Total',
  paid: 'Pagado',
  balance: 'Saldo pendiente',
  thank_you: 'Gracias por su preferencia.',
  payments: 'Pagos',
  no_payments: 'No se han registrado pagos.',
  payment_date: 'Fecha',
  payment_method: 'Método',
  payment_amount: 'Importe',
  payment_reference: 'Referencia',
  notes: 'Notas',
  generated_by: 'Generado por US Tow DISPATCH',
  terms: 'Términos',
};

interface TenantBranding {
  name: string;
  address?: Record<string, unknown> | null;
  phone?: string | null;
  email?: string | null;
  taglineEn?: string | null;
  taglineEs?: string | null;
  logoUrl?: string | null;
}

export interface RenderInvoicePdfInput {
  invoice: InvoiceDto;
  lineItems: InvoiceLineItemDto[];
  taxes: InvoiceTaxDto[];
  payments: PaymentDto[];
  tenant: TenantBranding;
  language?: PdfLanguage;
}

@Injectable()
export class InvoicePdfService {
  /**
   * Render an invoice to a PDF Buffer. The doc renders to memory rather than
   * to disk so the caller can persist via the StorageProvider in one step.
   */
  async renderInvoice(input: RenderInvoicePdfInput): Promise<Buffer> {
    const lang: PdfLanguage = input.language ?? 'en';
    const labels = lang === 'es' ? LABELS_ES : LABELS_EN;
    const isReceipt = input.invoice.invoiceType === 'cash_receipt';

    return new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'LETTER', margin: 48 });
        const chunks: Buffer[] = [];
        doc.on('data', (c: Buffer) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        // Header: tenant name + invoice/receipt header
        doc.fontSize(20).font('Helvetica-Bold').text(input.tenant.name, { continued: false });
        doc.fontSize(9).font('Helvetica');
        const addr = (input.tenant.address ?? {}) as Record<string, string | null | undefined>;
        const addrLine = [addr.street, addr.city, addr.state, addr.zip].filter((s) => s).join(', ');
        if (addrLine) doc.text(addrLine);
        const contactLine = [input.tenant.phone, input.tenant.email].filter(Boolean).join('  ·  ');
        if (contactLine) doc.text(contactLine);

        // Right-aligned title block.
        const titleY = doc.y - 60;
        doc
          .fontSize(24)
          .font('Helvetica-Bold')
          .text(isReceipt ? labels.receipt : labels.invoice, 380, titleY < 48 ? 48 : titleY, {
            width: 180,
            align: 'right',
          });
        doc.fontSize(10).font('Helvetica');
        doc.text(`${labels.invoice_number}: ${input.invoice.invoiceNumber}`, 380, doc.y, {
          width: 180,
          align: 'right',
        });
        if (input.invoice.issuedAt) {
          doc.text(`${labels.invoice_date}: ${formatDate(input.invoice.issuedAt)}`, 380, doc.y, {
            width: 180,
            align: 'right',
          });
        }
        if (input.invoice.dueAt && !isReceipt) {
          doc.text(`${labels.due_date}: ${formatDate(input.invoice.dueAt)}`, 380, doc.y, {
            width: 180,
            align: 'right',
          });
        }
        if (input.invoice.paidAt) {
          doc.text(`${labels.paid_date}: ${formatDate(input.invoice.paidAt)}`, 380, doc.y, {
            width: 180,
            align: 'right',
          });
        }
        doc.text(
          `${labels.status}: ${invoiceStatusLabel[input.invoice.status as InvoiceStatus]}`,
          380,
          doc.y,
          { width: 180, align: 'right' },
        );
        doc.text(`${labels.terms}: ${humanTerms(input.invoice.terms, lang)}`, 380, doc.y, {
          width: 180,
          align: 'right',
        });

        // Bill-to block
        doc.moveDown(2);
        doc.font('Helvetica-Bold').fontSize(10).text(labels.bill_to, 48);
        doc.font('Helvetica').fontSize(10);
        const bill = (input.invoice.billingAddress ?? {}) as Record<
          string,
          string | null | undefined
        >;
        if (bill.name) doc.text(bill.name);
        if (bill.street) doc.text(bill.street);
        const billCityLine = [bill.city, bill.state, bill.zip].filter(Boolean).join(', ');
        if (billCityLine) doc.text(billCityLine);
        if (bill.email) doc.text(bill.email);
        if (bill.phone) doc.text(bill.phone);

        doc.moveDown(1);
        doc
          .font('Helvetica')
          .fontSize(9)
          .fillColor('#666666')
          .text(invoiceTypeLabel[input.invoice.invoiceType as InvoiceType]);
        doc.fillColor('#000000');

        // Line items table
        doc.moveDown(0.8);
        const tableTop = doc.y;
        const colDescX = 48;
        const colQtyX = 320;
        const colUnitX = 380;
        const colTotalX = 500;

        doc.font('Helvetica-Bold').fontSize(10);
        doc.text(labels.description, colDescX, tableTop);
        doc.text(labels.qty, colQtyX, tableTop, { width: 50, align: 'right' });
        doc.text(labels.unit_price, colUnitX, tableTop, { width: 100, align: 'right' });
        doc.text(labels.line_total, colTotalX, tableTop, { width: 60, align: 'right' });
        doc
          .moveTo(48, doc.y + 4)
          .lineTo(560, doc.y + 4)
          .strokeColor('#cccccc')
          .stroke();
        doc.moveDown(0.5);
        doc.font('Helvetica').fontSize(10).fillColor('#000000');

        for (const li of input.lineItems) {
          const rowY = doc.y + 4;
          doc.text(li.description, colDescX, rowY, { width: 260 });
          doc.text(formatQuantity(li.quantity, li.unit), colQtyX, rowY, {
            width: 50,
            align: 'right',
          });
          doc.text(formatMoney(li.unitPriceCents), colUnitX, rowY, {
            width: 100,
            align: 'right',
          });
          doc.text(formatMoney(li.lineTotalCents), colTotalX, rowY, {
            width: 60,
            align: 'right',
          });
          // Move below the longest cell (description may wrap).
          const measured = doc.heightOfString(li.description, { width: 260 });
          doc.y = rowY + Math.max(measured, 14);
          if (doc.y > 700) {
            doc.addPage();
          }
        }

        doc
          .moveTo(380, doc.y + 6)
          .lineTo(560, doc.y + 6)
          .strokeColor('#cccccc')
          .stroke();
        doc.moveDown(0.6);

        // Totals stack
        const writeTotal = (label: string, amount: string, bold = false): void => {
          if (bold) doc.font('Helvetica-Bold');
          else doc.font('Helvetica');
          doc.fontSize(10);
          const y = doc.y;
          doc.text(label, 380, y, { width: 100, align: 'right' });
          doc.text(amount, colTotalX, y, { width: 60, align: 'right' });
        };
        writeTotal(labels.subtotal, formatMoney(input.invoice.subtotalCents));
        for (const t of input.taxes) {
          writeTotal(`${t.taxName} (${t.taxRatePct}%)`, formatMoney(t.taxAmountCents));
        }
        if (input.invoice.taxCents > 0 && input.taxes.length === 0) {
          writeTotal(labels.tax, formatMoney(input.invoice.taxCents));
        }
        writeTotal(labels.total, formatMoney(input.invoice.totalCents), true);
        if (input.invoice.paidCents !== 0) {
          writeTotal(labels.paid, `(${formatMoney(input.invoice.paidCents)})`);
          writeTotal(labels.balance, formatMoney(input.invoice.balanceCents), true);
        }

        // Payments section
        if (input.payments.length > 0) {
          doc.moveDown(2);
          doc.font('Helvetica-Bold').fontSize(11).text(labels.payments, 48);
          doc.font('Helvetica').fontSize(9);
          for (const p of input.payments) {
            doc.text(
              `${formatDate(p.receivedAt)}  ·  ${paymentMethodLabel[p.paymentMethod as PaymentMethod]}  ·  ${formatMoney(p.amountCents)}${
                p.referenceNumber ? `  ·  ${labels.payment_reference}: ${p.referenceNumber}` : ''
              }`,
              48,
            );
          }
        }

        // Notes / footer
        if (input.invoice.notes) {
          doc.moveDown(2);
          doc.font('Helvetica-Bold').fontSize(10).text(labels.notes, 48);
          doc.font('Helvetica').fontSize(10).text(input.invoice.notes, 48);
        }

        doc.fontSize(9).fillColor('#888888');
        const tagline = (lang === 'es' ? input.tenant.taglineEs : input.tenant.taglineEn) ?? '';
        doc.text(`${labels.thank_you}${tagline ? ` ${tagline}` : ''}`, 48, 740, {
          width: 512,
          align: 'center',
        });
        doc.text(`${labels.generated_by}`, 48, 754, { width: 512, align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}

function formatMoney(cents: number): string {
  const sign = cents < 0 ? '-' : '';
  const abs = Math.abs(cents);
  const dollars = Math.floor(abs / 100);
  const remainder = abs % 100;
  const formatted = dollars.toLocaleString('en-US');
  return `${sign}$${formatted}.${String(remainder).padStart(2, '0')}`;
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().slice(0, 10);
}

function formatQuantity(quantity: string, unit: string): string {
  const n = Number(quantity);
  if (!Number.isFinite(n)) return `${quantity} ${unit}`;
  if (Number.isInteger(n)) return `${n} ${unit}`;
  return `${n.toFixed(2)} ${unit}`;
}

function humanTerms(terms: string, lang: PdfLanguage): string {
  const en: Record<string, string> = {
    due_on_receipt: 'Due on receipt',
    net_15: 'Net 15',
    net_30: 'Net 30',
    net_45: 'Net 45',
    net_60: 'Net 60',
    cod: 'COD',
    prepay: 'Prepay',
  };
  const es: Record<string, string> = {
    due_on_receipt: 'Pago al recibir',
    net_15: 'Neto 15',
    net_30: 'Neto 30',
    net_45: 'Neto 45',
    net_60: 'Neto 60',
    cod: 'Pago contra entrega',
    prepay: 'Prepago',
  };
  return (lang === 'es' ? es : en)[terms] ?? terms;
}
