/**
 * RepoFormPdfService — renders the statutory repossession notices to PDF
 * (Repo Compliance, Session 51).
 *
 * ONE renderer, driven by the per-state rule config + the form type, covers
 * all 51 jurisdictions × 3 form types (pre-repo right-to-cure, post-repo
 * notice of intent to dispose, deficiency explanation) = 153 logical
 * templates. A separate file per template would be 153× the surface for the
 * same coverage; the per-state text comes from the rule config.
 *
 * No official state PDF form was sourced for this session, so each notice is a
 * compliant text document that cites the governing statute and states the
 * collateral, the amounts, the cure/redemption right, and the key deadline.
 * The statute citations + day-counts are best-effort and require legal review
 * before production filing — see SESSION_51_DECISIONS.md. Documents are
 * rendered in English (statutory filing language); a bilingual courtesy line
 * is included in the cure/redemption-rights block.
 */
import { Injectable } from '@nestjs/common';
import type { RepoFormType, RepoStateRules } from '@ustowdispatch/shared';
import PDFDocument from 'pdfkit';

/** Summary of the collateral (vehicle) a repossession notice describes. */
export interface RepoCollateralSummary {
  vehicleDescription: string;
  vehicleVin?: string | null;
  licensePlate?: string | null;
  licenseState?: string | null;
  // Date the loan went into default (for the pre-repo notice).
  defaultDate?: string | null;
  // Date the vehicle was recovered (for the post-repo / deficiency notices).
  repossessedAt?: string | null;
  // Outstanding balance / amounts, in cents.
  payoffAmountCents: number;
  pastDueAmountCents: number;
  // Disposition figures (deficiency notice only).
  saleProceedsCents?: number | null;
}

export interface RenderRepoFormInput {
  formType: RepoFormType;
  state: string;
  rules: RepoStateRules;
  // The secured party (lender / its repossession agent) issuing the notice.
  creditorName: string;
  caseId: string;
  // For pre-repo this is the notice/default date; for post-repo it is unused
  // in favor of the repossession date carried on the collateral summary.
  noticeDate: Date;
  collateral: RepoCollateralSummary;
  recipientName?: string | null;
  recipientAddress?: string | null;
}

const DAY_MS = 86_400_000;

/**
 * The salient textual content of a repossession notice, independent of PDF
 * layout. Pulled out as a pure builder so the content is unit-testable without
 * decompressing the PDF stream — PDFKit deflates text streams by default, so
 * the rendered Buffer is not greppable. `draw()` sources its strings from this
 * so the document and the assertions can never drift.
 */
export interface RepoNoticeContent {
  caseId: string;
  state: string;
  statute: string;
  title: string;
  recipientHeading: string;
  noticeBody: string;
  rightsHeading: string;
  rightsBody: string;
  keyDateLabel: string;
  keyDate: string;
  footer: string;
}

function formatDay(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().slice(0, 10);
}

function formatMoney(cents: number): string {
  const dollars = Math.floor(Math.abs(cents) / 100);
  const remainder = Math.abs(cents) % 100;
  return `$${dollars.toLocaleString('en-US')}.${String(remainder).padStart(2, '0')}`;
}

export function buildRepoNoticeContent(input: RenderRepoFormInput): RepoNoticeContent {
  const { rules, collateral } = input;
  const base = {
    caseId: input.caseId,
    state: input.state,
    statute: rules.statute,
    footer: `Generated by US Tow DISPATCH for case ${input.caseId}. This document is a system-generated draft; verify statutory form and content requirements with legal counsel before filing or mailing.`,
  };

  if (input.formType === 'pre_repo_notice') {
    const cureDeadline = new Date(input.noticeDate.getTime() + rules.preRepoNoticeDays * DAY_MS);
    return {
      ...base,
      title: `NOTICE OF DEFAULT AND RIGHT TO CURE (${input.state})`,
      recipientHeading: 'TO THE DEBTOR / BUYER OF RECORD:',
      noticeBody: `You are in default on your secured obligation to ${input.creditorName} for the vehicle described below. The past-due amount is ${formatMoney(collateral.pastDueAmountCents)}. Under ${rules.statute}, you have the right to cure this default by paying the past-due amount within the period stated below. If you do not cure, the vehicle may be repossessed without further notice.`,
      rightsHeading: 'RIGHT TO CURE',
      rightsBody: `You may cure the default and reinstate the contract by paying ${formatMoney(collateral.pastDueAmountCents)} on or before the cure deadline. ${rules.reinstatementRight ? 'You have the right to reinstate the contract upon cure.' : 'Contact the creditor named above immediately to arrange payment.'}`,
      keyDateLabel: 'Cure deadline (no repossession before)',
      keyDate: formatDay(cureDeadline.toISOString()),
    };
  }

  if (input.formType === 'post_repo_notice') {
    const repoDate = collateral.repossessedAt
      ? new Date(collateral.repossessedAt)
      : input.noticeDate;
    const redeemBy = new Date(repoDate.getTime() + rules.redemptionDays * DAY_MS);
    return {
      ...base,
      title: `NOTICE OF INTENT TO DISPOSE OF COLLATERAL (${input.state})`,
      recipientHeading: 'TO THE DEBTOR / OBLIGOR OF RECORD:',
      noticeBody: `The vehicle described below was repossessed by or on behalf of ${input.creditorName} and will be sold at private or public disposition under ${rules.statute}. The amount required to redeem (full payoff) is ${formatMoney(collateral.payoffAmountCents)}. You will be liable for any deficiency remaining after the sale and any expenses of retaking, holding, and selling the vehicle.`,
      rightsHeading: 'RIGHT TO REDEEM',
      rightsBody: `You have the right to redeem the vehicle by paying the full amount owed plus expenses on or before the redemption deadline below. ${rules.reinstatementRight ? 'You may also have the right to reinstate the contract.' : ''} You may request an accounting of the unpaid indebtedness at no charge.`,
      keyDateLabel: 'Redemption deadline (sale no sooner than)',
      keyDate: formatDay(redeemBy.toISOString()),
    };
  }

  // deficiency_notice
  const proceeds = collateral.saleProceedsCents ?? 0;
  const deficiency = collateral.payoffAmountCents - proceeds;
  return {
    ...base,
    title: `EXPLANATION OF CALCULATION OF SURPLUS OR DEFICIENCY (${input.state})`,
    recipientHeading: 'TO THE DEBTOR / OBLIGOR OF RECORD:',
    noticeBody: `Following the disposition of the vehicle described below, ${input.creditorName} provides this explanation of the surplus or deficiency under ${rules.statute}. Disposition proceeds were ${formatMoney(proceeds)}; the amount owed was ${formatMoney(collateral.payoffAmountCents)}.`,
    rightsHeading: deficiency > 0 ? 'DEFICIENCY OWED' : 'SURPLUS DUE',
    rightsBody:
      deficiency > 0
        ? `A deficiency of ${formatMoney(deficiency)} remains owing and is due. You may request a further written explanation of how this figure was calculated.`
        : `A surplus of ${formatMoney(Math.abs(deficiency))} is due to you. You may request a further written explanation of how this figure was calculated.`,
    keyDateLabel: 'Disposition date',
    keyDate: formatDay(input.noticeDate.toISOString()),
  };
}

@Injectable()
export class RepoFormPdfService {
  /** Render the requested notice to a PDF Buffer (rendered to memory). */
  async renderForm(input: RenderRepoFormInput): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'LETTER', margin: 56 });
        const chunks: Buffer[] = [];
        doc.on('data', (c: Buffer) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        this.draw(doc, input);

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  private draw(doc: PDFKit.PDFDocument, input: RenderRepoFormInput): void {
    const content = buildRepoNoticeContent(input);
    const { collateral } = input;

    // Header — the secured party (creditor / repossession agent).
    doc.fontSize(16).font('Helvetica-Bold').text(input.creditorName, { align: 'left' });
    doc.moveDown(0.2);
    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#555555')
      .text('Secured party / repossession agent');
    doc.fillColor('#000000');

    // Title.
    doc.moveDown(1);
    doc.fontSize(15).font('Helvetica-Bold').text(content.title, { align: 'center' });
    doc.moveDown(0.3);
    doc
      .fontSize(9)
      .font('Helvetica-Oblique')
      .fillColor('#555555')
      .text(`Issued pursuant to ${content.statute}`, { align: 'center' });
    doc.fillColor('#000000');

    // Recipient block.
    doc.moveDown(1.2);
    doc.fontSize(10).font('Helvetica-Bold').text(content.recipientHeading);
    doc.font('Helvetica');
    doc.text(input.recipientName ?? '[Debtor / obligor of record]');
    if (input.recipientAddress) doc.text(input.recipientAddress);

    // Vehicle block.
    doc.moveDown(1);
    doc.font('Helvetica-Bold').text('COLLATERAL (VEHICLE)');
    doc.font('Helvetica');
    this.kv(doc, 'Description', collateral.vehicleDescription);
    this.kv(doc, 'VIN', collateral.vehicleVin ?? 'Not available');
    this.kv(
      doc,
      'License plate',
      collateral.licensePlate
        ? `${collateral.licensePlate}${collateral.licenseState ? ` (${collateral.licenseState})` : ''}`
        : 'Not available',
    );
    if (collateral.repossessedAt) {
      this.kv(doc, 'Date repossessed', formatDay(collateral.repossessedAt));
    }
    this.kv(doc, 'Past-due amount', formatMoney(collateral.pastDueAmountCents));
    this.kv(doc, 'Full payoff amount', formatMoney(collateral.payoffAmountCents));

    // Body.
    doc.moveDown(1);
    doc.font('Helvetica-Bold').text('NOTICE');
    doc.font('Helvetica');
    doc.text(content.noticeBody, { align: 'left' });

    // Rights block.
    doc.moveDown(0.6);
    doc.font('Helvetica-Bold').text(content.rightsHeading);
    doc.font('Helvetica');
    doc.text(content.rightsBody);
    doc
      .fontSize(8.5)
      .fillColor('#555555')
      .text(
        'Aviso: Usted puede tener derecho a recuperar o reclamar el vehículo pagando las cantidades adeudadas. Comuníquese de inmediato con el acreedor indicado arriba.',
      );
    doc.fontSize(10).fillColor('#000000');

    // Key date + breach-of-peace standard.
    doc.moveDown(0.8);
    doc.font('Helvetica-Bold').text('KEY DATES');
    doc.font('Helvetica');
    this.kv(doc, content.keyDateLabel, content.keyDate);
    this.kv(doc, 'Repossession standard', input.rules.breachOfPeaceStandard);

    // Signature.
    doc.moveDown(1.5);
    doc.font('Helvetica').text('_______________________________________', { continued: false });
    doc.text('Authorized agent, secured party');
    doc.text(`Date: ${formatDay(new Date().toISOString())}`);

    // Footer disclaimer.
    doc
      .fontSize(7.5)
      .fillColor('#888888')
      .text(content.footer, 56, 740, { width: 484, align: 'center' });
    doc.fillColor('#000000');
  }

  private kv(doc: PDFKit.PDFDocument, label: string, value: string): void {
    const y = doc.y + 2;
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .text(`${label}:`, 56, y, { width: 200, continued: false });
    doc.font('Helvetica').fontSize(9).text(value, 260, y, { width: 280 });
  }
}
