/**
 * RepoFormPdfService — renders the statutory repossession notices to PDF
 * (Repo Compliance, Session 50).
 *
 * ONE renderer, driven by the per-state rule config + the form type, covers
 * all 10 states × 2 form types (post-repossession notice + personal-property
 * notice) = the 20 logical templates. The per-state text (statute, redemption
 * window, hold period) comes from the rule config.
 *
 * No official state PDF form was sourced for this session, so each notice is a
 * compliant text document that cites the governing statute and states the
 * vehicle, the debtor, the recovery date, the redemption/cure deadline, and
 * the personal-property hold-until date + release method. The citations +
 * day-counts are best-effort and require legal review before production filing
 * — see SESSION_50_DECISIONS.md. Rendered in English (statutory filing
 * language) with a bilingual courtesy line in the rights block.
 */
import { Injectable } from '@nestjs/common';
import type { RepoFormType, RepoStateRules } from '@ustowdispatch/shared';
import PDFDocument from 'pdfkit';

export interface RenderRepoFormInput {
  formType: RepoFormType;
  state: string;
  rules: RepoStateRules;
  tenantName: string;
  repoCaseId: string;
  recoveredAt: Date;
  debtorName?: string | null;
  debtorAddress?: string | null;
  vehicleDescription?: string | null;
  vehicleVin?: string | null;
  licensePlate?: string | null;
  accruedChargesCents?: number | null;
}

const DAY_MS = 86_400_000;

/**
 * The salient textual content of a repossession notice, independent of PDF
 * layout. Pulled out as a pure builder so the content (statute citation, case
 * id, title, body, deadlines) is unit-testable without decompressing the PDF
 * stream — PDFKit deflates text streams by default, so the rendered Buffer is
 * not greppable. `draw()` sources its strings from this so the document and
 * the assertions can never drift.
 */
export interface RepoNoticeContent {
  repoCaseId: string;
  state: string;
  statute: string;
  title: string;
  recipientHeading: string;
  noticeBody: string;
  redemptionDeadline: string | null;
  personalPropertyHoldUntil: string;
  releaseMethod: string;
  footer: string;
}

export function buildRepoNoticeContent(input: RenderRepoFormInput): RepoNoticeContent {
  const isPersonalProperty = input.formType === 'personal_property_notice';
  const recoveredMs = input.recoveredAt.getTime();
  const redemptionDeadline =
    input.rules.redemptionPeriodDays > 0
      ? formatDay(new Date(recoveredMs + input.rules.redemptionPeriodDays * DAY_MS).toISOString())
      : null;
  const holdUntil = formatDay(
    new Date(recoveredMs + input.rules.personalPropertyHoldDays * DAY_MS).toISOString(),
  );
  return {
    repoCaseId: input.repoCaseId,
    state: input.state,
    statute: input.rules.statute,
    title: isPersonalProperty
      ? `NOTICE OF PERSONAL PROPERTY RECOVERED WITH VEHICLE (${input.state})`
      : `NOTICE OF REPOSSESSION AND RIGHT TO REDEEM (${input.state})`,
    recipientHeading: 'TO THE DEBTOR / REGISTERED OWNER:',
    noticeBody: isPersonalProperty
      ? `Personal property left in the above-described vehicle when it was repossessed by ${input.tenantName} is being held for you. You may reclaim it without charge. Property not claimed by the hold-until date below may be disposed of as permitted under ${input.rules.statute}.`
      : `You are hereby notified that the above-described vehicle was repossessed by ${input.tenantName} under ${input.rules.statute}. Unless you redeem the vehicle or cure the default as described below, the vehicle will be sold or otherwise disposed of to satisfy the obligation, and you may be liable for any deficiency.`,
    redemptionDeadline,
    personalPropertyHoldUntil: holdUntil,
    releaseMethod: input.rules.personalPropertyReleaseMethod,
    footer: `Generated by US Tow DISPATCH for repo case ${input.repoCaseId}. This document is a system-generated draft; verify statutory form and content requirements with legal counsel before filing or mailing.`,
  };
}

@Injectable()
export class RepoFormPdfService {
  /** Render the requested notice to a PDF Buffer (rendered to memory). */
  async renderForm(input: RenderRepoFormInput): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'LETTER', margin: 56 });
        const chunks: Buffer[] = [];
        doc.on('data', (c: Buffer) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        this.draw(doc, input);

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  private draw(doc: PDFKit.PDFDocument, input: RenderRepoFormInput): void {
    const isPersonalProperty = input.formType === 'personal_property_notice';
    const content = buildRepoNoticeContent(input);

    // Header — the lender / repossession agent.
    doc.fontSize(16).font('Helvetica-Bold').text(input.tenantName, { align: 'left' });
    doc.moveDown(0.2);
    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#555555')
      .text('Secured party / repossession agent');
    doc.fillColor('#000000');

    // Title.
    doc.moveDown(1);
    doc.fontSize(15).font('Helvetica-Bold').text(content.title, { align: 'center' });
    doc.moveDown(0.3);
    doc
      .fontSize(9)
      .font('Helvetica-Oblique')
      .fillColor('#555555')
      .text(`Issued pursuant to ${content.statute}`, { align: 'center' });
    doc.fillColor('#000000');

    // Recipient block.
    doc.moveDown(1.2);
    doc.fontSize(10).font('Helvetica-Bold').text(content.recipientHeading);
    doc.font('Helvetica');
    doc.text(input.debtorName ?? '[Debtor / registered owner of record]');
    if (input.debtorAddress) doc.text(input.debtorAddress);

    // Vehicle block.
    doc.moveDown(1);
    doc.font('Helvetica-Bold').text('VEHICLE REPOSSESSED');
    doc.font('Helvetica');
    this.kv(doc, 'Description', input.vehicleDescription ?? 'Not available');
    this.kv(doc, 'VIN', input.vehicleVin ?? 'Not available');
    this.kv(doc, 'License plate', input.licensePlate ?? 'Not available');
    this.kv(doc, 'Date repossessed', formatDay(input.recoveredAt.toISOString()));
    if (input.accruedChargesCents != null) {
      this.kv(doc, 'Charges to date', formatMoney(input.accruedChargesCents));
    }

    // Body.
    doc.moveDown(1);
    doc.font('Helvetica-Bold').text('NOTICE');
    doc.font('Helvetica');
    doc.text(content.noticeBody, { align: 'left' });

    if (!isPersonalProperty) {
      doc.moveDown(0.6);
      doc.font('Helvetica-Bold').text('RIGHT TO REDEEM / CURE');
      doc.font('Helvetica');
      if (content.redemptionDeadline) {
        this.kv(doc, 'Redeem or cure on or before', content.redemptionDeadline);
        this.kv(doc, 'Redemption period', `${input.rules.redemptionPeriodDays} days`);
      } else {
        doc.text(
          'This state does not provide a fixed pre-sale redemption window; you may have a right to cure the default and a post-sale right to any surplus. Contact the secured party named above without delay.',
        );
      }
      if (input.rules.cureRight) {
        this.kv(doc, 'Right to cure', `${input.rules.cureRightDays} days`);
      }
    }

    // Personal-property block (always present — property obligations attach to
    // every repossession).
    doc.moveDown(0.6);
    doc.font('Helvetica-Bold').text('PERSONAL PROPERTY');
    doc.font('Helvetica');
    this.kv(doc, 'Hold-until date', content.personalPropertyHoldUntil);
    this.kv(doc, 'Hold period', `${input.rules.personalPropertyHoldDays} days`);
    this.kv(doc, 'Release method', humanizeMethod(content.releaseMethod));

    doc
      .fontSize(8.5)
      .fillColor('#555555')
      .text(
        'Aviso: Usted tiene derecho a recuperar su propiedad personal y, según el estado, a redimir el vehículo pagando lo adeudado antes de la venta. Comuníquese de inmediato con el acreedor.',
      );
    doc.fontSize(10).fillColor('#000000');

    // Signature.
    doc.moveDown(1.5);
    doc.font('Helvetica').text('_______________________________________', { continued: false });
    doc.text('Authorized agent, secured party');
    doc.text(`Date: ${formatDay(new Date().toISOString())}`);

    // Footer disclaimer.
    doc
      .fontSize(7.5)
      .fillColor('#888888')
      .text(content.footer, 56, 740, { width: 484, align: 'center' });
    doc.fillColor('#000000');
  }

  private kv(doc: PDFKit.PDFDocument, label: string, value: string): void {
    const y = doc.y + 2;
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .text(`${label}:`, 56, y, { width: 200, continued: false });
    doc.font('Helvetica').fontSize(9).text(value, 260, y, { width: 280 });
  }
}

function humanizeMethod(method: string): string {
  switch (method) {
    case 'owner_pickup_after_notice':
      return 'Owner pickup after notice';
    case 'mail_return':
      return 'Returned by mail';
    case 'disposal_after_hold':
      return 'Disposed of after the hold period';
    default:
      return method;
  }
}

function formatMoney(cents: number): string {
  const dollars = Math.floor(Math.abs(cents) / 100);
  const remainder = Math.abs(cents) % 100;
  return `$${dollars.toLocaleString('en-US')}.${String(remainder).padStart(2, '0')}`;
}

function formatDay(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().slice(0, 10);
}
