-- =====================================================================
-- 0051_repo_compliance.sql  (Repo Compliance — Session 51)
--
-- Creates and seeds repo_state_rules: the per-state statutory rule config for
-- the self-help repossession compliance workflow, covering all 50 states + DC
-- (51 rows).
--
-- BACKGROUND: the planned Session 49 (repo-core engine) and Session 50 (first
-- 10 state configs) never landed on master, so unlike the lien module — where
-- 0038 created lien_state_rules and 0044 only INSERTed the remaining states —
-- this single migration both CREATEs the table and seeds all 51 rows. See
-- SESSION_51_DECISIONS.md for why S51 was built self-contained.
--
-- repo_state_rules is GLOBAL reference data: no tenant_id, no RLS. The statute
-- config is the same for every operator in a given state; app_user reads it
-- via the default-privilege SELECT grant (0002_roles.sql). This mirrors the
-- lien_state_rules pattern exactly.
--
-- The rule-engine runtime source of truth is
-- apps/api/src/modules/repo-compliance/state-rules.config.ts; this table
-- mirrors it for queryability / auditability. These rows were GENERATED
-- directly from that config (and a parity test asserts they stay in sync), so
-- the two cannot drift. If the TS config changes a value, ship a follow-up
-- migration that re-seeds it (DO UPDATE) rather than editing this one.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + ON CONFLICT (state) DO NOTHING.
-- Re-running is a no-op.
--
-- ⚠️  LEGAL DISCLAIMER: the day-counts and posture flags are best-effort
-- interpretations of each jurisdiction's repossession / UCC Article 9 /
-- consumer-credit statutes (cited in the `statute` field) and MUST be reviewed
-- by counsel against the current state code before any production repossession
-- runs through this code. See SESSION_51_DECISIONS.md.
--
-- Down (rollback): the rows are reference data.
--   DROP TABLE IF EXISTS repo_state_rules;
--   DROP FUNCTION IF EXISTS fn_repo_set_updated_at();
-- =====================================================================

-- Generic updated_at stamper for repo-compliance reference tables.
CREATE OR REPLACE FUNCTION fn_repo_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$$;

-- ---------------------------------------------------------------------
-- repo_state_rules  (GLOBAL reference data — NOT tenant-scoped)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS repo_state_rules (
  state       text PRIMARY KEY,
  rules       jsonb NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE repo_state_rules DROP CONSTRAINT IF EXISTS repo_state_rules_state_format;
ALTER TABLE repo_state_rules ADD CONSTRAINT repo_state_rules_state_format
  CHECK (state ~ '^[A-Z]{2}$');

DROP TRIGGER IF EXISTS trg_repo_state_rules_set_updated_at ON repo_state_rules;
CREATE TRIGGER trg_repo_state_rules_set_updated_at
  BEFORE UPDATE ON repo_state_rules
  FOR EACH ROW EXECUTE FUNCTION fn_repo_set_updated_at();

-- Reference SELECT for app_user (default-privilege grant covers it; explicit
-- here for clarity / re-runnability on environments seeded before 0002).
GRANT SELECT ON repo_state_rules TO app_user;

-- ---------------------------------------------------------------------
-- Seed all 50 states + DC. Generated from state-rules.config.ts.
-- ---------------------------------------------------------------------
INSERT INTO repo_state_rules (state, rules) VALUES
  ('CA', '{"statute":"CA Comm. Code 9609/9611/9614/9616/9623; Civ. Code 2983.2-2983.3 (Rees-Levering)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":60,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('TX', '{"statute":"TX Bus. & Com. Code 9.609/9.611/9.614/9.616/9.623; Fin. Code 348","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('FL', '{"statute":"FL Stat. 679.609/679.611/679.614/679.616/679.623 (UCC Art. 9)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NY', '{"statute":"NY UCC 9-609/9-611/9-614/9-616/9-623; Pers. Prop. Law Art. 9 (MVRISA)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('GA', '{"statute":"GA Code 11-9-609/11-9-611/11-9-614/11-9-616/11-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NC', '{"statute":"NC Gen. Stat. 25-9-609/25-9-611/25-9-614/25-9-616/25-9-623; Ch. 25A (RISA)","preRepoNoticeRequired":true,"preRepoNoticeDays":15,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('OH', '{"statute":"OH Rev. Code 1309.609/1309.611/1309.614/1309.616/1309.623; 1317 (RISA)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('IL', '{"statute":"IL 810 ILCS 5/9-609..9-623; 815 ILCS 375 (MV Retail Installment)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('PA', '{"statute":"PA 13 Pa.C.S. 9609/9611/9614/9616/9623; 12 P.S. 6251 (MVSFA) / Goodwin","preRepoNoticeRequired":true,"preRepoNoticeDays":15,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MI', '{"statute":"MI Comp. Laws 440.9609/440.9611/440.9614/440.9616/440.9623; 492.114","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('AK', '{"statute":"AK Stat. 45.29.609/45.29.611/45.29.614/45.29.616/45.29.623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('AL', '{"statute":"AL Code 7-9A-609/7-9A-611/7-9A-614/7-9A-616/7-9A-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('AR', '{"statute":"AR Code 4-9-609/4-9-611/4-9-614/4-9-616/4-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('AZ', '{"statute":"AZ Rev. Stat. 47-9609/47-9611/47-9614/47-9616/47-9623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('CO', '{"statute":"CO Rev. Stat. 4-9-609..4-9-623; 5-5-110/5-5-111 (UCCC right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('CT', '{"statute":"CT Gen. Stat. 42a-9-609..42a-9-623; 36a-785 (retail installment)","preRepoNoticeRequired":true,"preRepoNoticeDays":15,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('DC', '{"statute":"DC Code 28:9-609..28:9-623; 28-3812 (consumer credit right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":15,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('DE', '{"statute":"DE Code tit. 6 9-609/9-611/9-614/9-616/9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('HI', '{"statute":"HI Rev. Stat. 490:9-609/490:9-611/490:9-614/490:9-616/490:9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('IA', '{"statute":"IA Code 554.9609..554.9623; 537.5110/537.5111 (ICCC right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('ID', '{"statute":"ID Code 28-9-609..28-9-623; 28-45-110/28-45-111 (Credit Code cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('IN', '{"statute":"IN Code 26-1-9.1-609..623; 24-4.5-5-110/111 (IUCCC right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('KS', '{"statute":"KS Stat. 84-9-609..84-9-623; 16a-5-110/16a-5-111 (UCCC right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('KY', '{"statute":"KY Rev. Stat. 355.9-609/355.9-611/355.9-614/355.9-616/355.9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('LA', '{"statute":"LA Rev. Stat. 10:9-609..10:9-623; 6:966 (Consumer Credit Law)","preRepoNoticeRequired":true,"preRepoNoticeDays":10,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MA', '{"statute":"MA Gen. Laws 106:9-609..9-623; 255B:20B (right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":21,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":21,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MD', '{"statute":"MD Com. Law 9-609/9-611/9-614/9-616/9-623; 12-1021 (CLEC repossession)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('ME', '{"statute":"ME Rev. Stat. tit. 11 9-1609..9-1623; tit. 9-A 5-110/5-111 (cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":14,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MN', '{"statute":"MN Stat. 336.9-609/336.9-611/336.9-614/336.9-616/336.9-623; 168.66 et seq","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MO', '{"statute":"MO Rev. Stat. 400.9-609..400.9-623; 408.554/408.555 (right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MS', '{"statute":"MS Code 75-9-609/75-9-611/75-9-614/75-9-616/75-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('MT', '{"statute":"MT Code 30-9A-609/30-9A-611/30-9A-614/30-9A-616/30-9A-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('ND', '{"statute":"ND Cent. Code 41-09-609..41-09-623; 51-13 (retail installment)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NE', '{"statute":"NE Rev. Stat. 9-609..9-623 (UCC); 45-1,107 (NILB right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NH', '{"statute":"NH Rev. Stat. 382-A:9-609..9-623; 361-A (retail installment)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NJ', '{"statute":"NJ Stat. 12A:9-609..12A:9-623; 17:16C (Retail Installment Sales Act)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NM', '{"statute":"NM Stat. 55-9-609/55-9-611/55-9-614/55-9-616/55-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('NV', '{"statute":"NV Rev. Stat. 104.9609/104.9611/104.9614/104.9616/104.9623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('OK', '{"statute":"OK Stat. tit. 12A 1-9-609..623; tit. 14A 5-110/5-111 (UCCC cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('OR', '{"statute":"OR Rev. Stat. 79.0609/79.0611/79.0614/79.0616/79.0623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('RI', '{"statute":"RI Gen. Laws 6A-9-609..6A-9-623; 6-27 (retail installment)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('SC', '{"statute":"SC Code 36-9-609..36-9-623; 37-5-110/37-5-111 (Consumer Protection cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('SD', '{"statute":"SD Codified Laws 57A-9-609..57A-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('TN', '{"statute":"TN Code 47-9-609/47-9-611/47-9-614/47-9-616/47-9-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('UT', '{"statute":"UT Code 70A-9a-609..623; 70C-7-101 et seq (Consumer Credit cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('VA', '{"statute":"VA Code 8.9A-609/8.9A-611/8.9A-614/8.9A-616/8.9A-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('VT', '{"statute":"VT Stat. tit. 9A 9-609..9-623; tit. 9 2455 (retail installment)","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('WA', '{"statute":"WA Rev. Code 62A.9A-609/62A.9A-611/62A.9A-614/62A.9A-616/62A.9A-623","preRepoNoticeRequired":false,"preRepoNoticeDays":0,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":false,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('WI', '{"statute":"WI Stat. 409.609..409.623; 425.104/425.105 (Consumer Act right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":15,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('WV', '{"statute":"WV Code 46-9-609..46-9-623; 46A-2-106 (CCPA right to cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb),
  ('WY', '{"statute":"WY Stat. 34.1-9-609..34.1-9-623; 40-14-521/40-14-522 (UCCC cure)","preRepoNoticeRequired":true,"preRepoNoticeDays":20,"breachOfPeaceStandard":"no force, no threat, no fraud, no breach of close (UCC 9-609)","certifiedNoticeRequired":true,"postRepoNoticeDays":10,"redemptionDays":15,"personalPropertyHoldDays":30,"reinstatementRight":true,"deficiencyNoticeRequired":true,"valueTiers":{"lowMaxCents":250000,"highMinCents":1000000}}'::jsonb)
ON CONFLICT (state) DO NOTHING;
