/**
 * DamageReportPdfService — renders damage-analysis reports with PDFKit
 * (Photo Damage Analysis, Session 42).
 *
 * Mirrors InvoicePdfService: imperative PDFKit, renders to a Buffer (the
 * controller streams it; no disk, no storage coupling), bilingual EN/ES.
 *
 * Photo overlays: rather than embedding the source S3 image bytes (which
 * would couple rendering to object storage and make the output non-
 * deterministic / untestable), each bounding box is drawn as a labelled
 * rectangle on a normalised photo frame — the operator sees WHERE on the
 * photo the model flagged damage. Embedding the real photo behind the
 * overlay is a deferred enhancement (see SESSION_42_DECISIONS.md).
 */
import { Injectable } from '@nestjs/common';
import type {
  CompareResult,
  DamageAnalysisDto,
  DamageComparisonDto,
  DamageFindingDto,
  DamageSeverity,
} from '@ustowdispatch/shared';
import PDFDocument from 'pdfkit';

export type PdfLanguage = 'en' | 'es';

export interface DamageReportContext {
  jobReference: string;
  vehicleDescription: string;
  operatorName: string;
  language?: PdfLanguage;
}

export interface RenderAnalysisReportInput {
  analysis: DamageAnalysisDto;
  findings: DamageFindingDto[];
  context: DamageReportContext;
}

export interface RenderComparisonReportInput {
  comparison: DamageComparisonDto;
  result: CompareResult;
  context: DamageReportContext;
}

type DamageLabels = {
  analysisTitle: string;
  comparisonTitle: string;
  job: string;
  vehicle: string;
  phase: string;
  generated: string;
  operator: string;
  analyzedBy: string;
  status: string;
  findings: string;
  area: string;
  severity: string;
  confidence: string;
  description: string;
  noFindings: string;
  overlays: string;
  newDamage: string;
  preExisting: string;
  inconclusive: string;
  summary: string;
  operatorOverride: string;
  dismissed: string;
  footer: string;
};

const LABELS: Record<PdfLanguage, DamageLabels> = {
  en: {
    analysisTitle: 'VEHICLE DAMAGE ANALYSIS',
    comparisonTitle: 'PRE / POST-TOW DAMAGE COMPARISON',
    job: 'Job',
    vehicle: 'Vehicle',
    phase: 'Phase',
    generated: 'Generated',
    operator: 'Operator',
    analyzedBy: 'Analyzed by',
    status: 'Status',
    findings: 'Findings',
    area: 'Area',
    severity: 'Severity',
    confidence: 'Confidence',
    description: 'Description',
    noFindings: 'No damage detected.',
    overlays: 'Damage locations (normalised photo frames)',
    newDamage: 'NEW DAMAGE (post-tow, not present pre-tow)',
    preExisting: 'Pre-existing damage',
    inconclusive: 'Inconclusive',
    summary: 'Summary',
    operatorOverride: 'operator override',
    dismissed: 'dismissed',
    footer: 'Generated by US Tow Dispatch · AI-assisted; operator review required',
  },
  es: {
    analysisTitle: 'ANÁLISIS DE DAÑOS DEL VEHÍCULO',
    comparisonTitle: 'COMPARACIÓN DE DAÑOS ANTES / DESPUÉS DEL REMOLQUE',
    job: 'Servicio',
    vehicle: 'Vehículo',
    phase: 'Etapa',
    generated: 'Generado',
    operator: 'Operador',
    analyzedBy: 'Analizado por',
    status: 'Estado',
    findings: 'Hallazgos',
    area: 'Área',
    severity: 'Gravedad',
    confidence: 'Confianza',
    description: 'Descripción',
    noFindings: 'No se detectaron daños.',
    overlays: 'Ubicación de daños (marcos de foto normalizados)',
    newDamage: 'DAÑO NUEVO (posterior al remolque, ausente antes)',
    preExisting: 'Daño preexistente',
    inconclusive: 'No concluyente',
    summary: 'Resumen',
    operatorOverride: 'ajuste del operador',
    dismissed: 'descartado',
    footer: 'Generado por US Tow Dispatch · Asistido por IA; requiere revisión del operador',
  },
};

const SEVERITY_COLOR: Record<DamageSeverity, string> = {
  none: '#9ca3af',
  minor: '#6b7280',
  moderate: '#d97706',
  severe: '#dc2626',
};

@Injectable()
export class DamageReportPdfService {
  async renderAnalysisReport(input: RenderAnalysisReportInput): Promise<Buffer> {
    const lang: PdfLanguage = input.context.language ?? 'en';
    const t = LABELS[lang];
    return this.render((doc) => {
      this.cover(doc, t.analysisTitle, input.context, lang, [
        [t.phase, humanPhase(input.analysis.phase, lang)],
        [t.status, input.analysis.status],
        [t.analyzedBy, `${input.analysis.provider} · ${input.analysis.model ?? '—'}`],
      ]);
      this.findingsTable(doc, t, input.findings);
      this.overlays(doc, t, input.findings);
      this.footer(doc, t);
    });
  }

  async renderComparisonReport(input: RenderComparisonReportInput): Promise<Buffer> {
    const lang: PdfLanguage = input.context.language ?? 'en';
    const t = LABELS[lang];
    return this.render((doc) => {
      this.cover(doc, t.comparisonTitle, input.context, lang, [
        [t.summary, input.comparison.comparisonSummary ?? '—'],
        [t.confidence, `≥ ${Math.round(input.comparison.confidenceThreshold * 100)}%`],
      ]);

      // New damage is the evidentiary core — render it first and prominently.
      doc.moveDown(1);
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#dc2626').text(t.newDamage, 48);
      doc.fillColor('#000000');
      this.entryList(doc, t, input.result.newDamage, lang);

      doc.moveDown(1);
      doc.font('Helvetica-Bold').fontSize(12).fillColor('#000000').text(t.preExisting, 48);
      this.entryList(doc, t, input.result.preExisting, lang);

      doc.moveDown(1);
      doc.font('Helvetica-Bold').fontSize(12).text(t.inconclusive, 48);
      this.entryList(doc, t, input.result.inconclusive, lang);

      this.footer(doc, t);
    });
  }

  // ------------------------------------------------------------------

  private render(draw: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'LETTER', margin: 48 });
        const chunks: Buffer[] = [];
        doc.on('data', (c: Buffer) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));
        draw(doc);
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  private cover(
    doc: PDFKit.PDFDocument,
    title: string,
    ctx: DamageReportContext,
    lang: PdfLanguage,
    extra: Array<[string, string]>,
  ): void {
    const t = LABELS[lang];
    doc.fontSize(20).font('Helvetica-Bold').text('US Tow Dispatch', 48, 48);
    doc.fontSize(15).font('Helvetica-Bold').fillColor('#111827').text(title);
    doc.moveDown(0.8);
    doc.fontSize(10).font('Helvetica').fillColor('#000000');
    const rows: Array<[string, string]> = [
      [t.job, ctx.jobReference],
      [t.vehicle, ctx.vehicleDescription],
      [t.operator, ctx.operatorName],
      [t.generated, `${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC`],
      ...extra,
    ];
    for (const [label, value] of rows) {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(value);
    }
    doc
      .moveTo(48, doc.y + 6)
      .lineTo(560, doc.y + 6)
      .strokeColor('#cccccc')
      .stroke();
  }

  private findingsTable(
    doc: PDFKit.PDFDocument,
    t: DamageLabels,
    findings: DamageFindingDto[],
  ): void {
    doc.moveDown(1);
    doc.font('Helvetica-Bold').fontSize(12).text(t.findings, 48);
    doc.moveDown(0.4);
    if (findings.length === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#6b7280').text(t.noFindings, 48);
      doc.fillColor('#000000');
      return;
    }
    const top = doc.y;
    const cols = { area: 48, sev: 180, conf: 290, desc: 360 };
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#374151');
    doc.text(t.area, cols.area, top);
    doc.text(t.severity, cols.sev, top);
    doc.text(t.confidence, cols.conf, top);
    doc.text(t.description, cols.desc, top);
    doc
      .moveTo(48, doc.y + 3)
      .lineTo(560, doc.y + 3)
      .strokeColor('#cccccc')
      .stroke();
    doc.moveDown(0.4);
    doc.fillColor('#000000').font('Helvetica').fontSize(9);
    for (const f of findings) {
      const y = doc.y + 3;
      const sev = (f.operatorSeverity ?? f.severity) as DamageSeverity;
      const tags = [f.operatorSeverity ? t.operatorOverride : '', f.isDismissed ? t.dismissed : '']
        .filter(Boolean)
        .join(', ');
      doc.fillColor('#000000').text(humanArea(f.area), cols.area, y, { width: 125 });
      doc.fillColor(SEVERITY_COLOR[sev]).text(sev, cols.sev, y, { width: 100 });
      doc.fillColor('#000000').text(`${f.confidencePct}%`, cols.conf, y, { width: 60 });
      const desc = [f.description ?? '', tags ? `(${tags})` : ''].filter(Boolean).join(' ');
      doc.text(desc, cols.desc, y, { width: 200 });
      const measured = doc.heightOfString(desc || ' ', { width: 200 });
      doc.y = y + Math.max(measured, 12);
      if (doc.y > 700) doc.addPage();
    }
  }

  private overlays(doc: PDFKit.PDFDocument, t: DamageLabels, findings: DamageFindingDto[]): void {
    const withBox = findings.filter((f) => f.boundingBox);
    if (withBox.length === 0) return;
    doc.moveDown(1.2);
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#000000').text(t.overlays, 48);
    doc.moveDown(0.5);
    const frameW = 150;
    const frameH = 100;
    let x = 48;
    let y = doc.y;
    for (const f of withBox) {
      const box = f.boundingBox;
      if (!box) continue;
      if (y + frameH > 720) {
        doc.addPage();
        y = 48;
        x = 48;
      }
      // Photo frame.
      doc.rect(x, y, frameW, frameH).strokeColor('#9ca3af').lineWidth(1).stroke();
      // Bounding box (normalised → frame coords), clamped to the frame.
      const bx = x + Math.max(0, Math.min(1, box.x)) * frameW;
      const by = y + Math.max(0, Math.min(1, box.y)) * frameH;
      const bw = Math.max(0, Math.min(1, box.w)) * frameW;
      const bh = Math.max(0, Math.min(1, box.h)) * frameH;
      const sev = (f.operatorSeverity ?? f.severity) as DamageSeverity;
      doc
        .rect(bx, by, Math.max(bw, 4), Math.max(bh, 4))
        .strokeColor(SEVERITY_COLOR[sev])
        .lineWidth(2)
        .stroke();
      doc
        .fontSize(7)
        .fillColor('#374151')
        .font('Helvetica')
        .text(humanArea(f.area), x, y + frameH + 2, {
          width: frameW,
        });
      x += frameW + 20;
      if (x + frameW > 560) {
        x = 48;
        y += frameH + 24;
      }
    }
    doc.lineWidth(1).fillColor('#000000');
    doc.y = Math.max(doc.y, y + frameH + 24);
  }

  private entryList(
    doc: PDFKit.PDFDocument,
    t: DamageLabels,
    entries: CompareResult['newDamage'],
    _lang: PdfLanguage,
  ): void {
    doc.moveDown(0.3);
    if (entries.length === 0) {
      doc.font('Helvetica').fontSize(9).fillColor('#6b7280').text('—', 60);
      doc.fillColor('#000000');
      return;
    }
    doc.font('Helvetica').fontSize(9).fillColor('#000000');
    for (const e of entries) {
      if (doc.y > 710) doc.addPage();
      const prior = e.priorSeverity ? ` (was ${e.priorSeverity})` : '';
      doc
        .fillColor(SEVERITY_COLOR[e.severity])
        .font('Helvetica-Bold')
        .text(`• ${humanArea(e.area)} — ${e.severity}${prior}`, 60, doc.y, { continued: true });
      doc.fillColor('#374151').font('Helvetica').text(`  ${e.confidencePct}% · ${e.reason}`);
    }
    doc.fillColor('#000000');
  }

  private footer(doc: PDFKit.PDFDocument, t: DamageLabels): void {
    doc.fontSize(8).fillColor('#888888').font('Helvetica');
    doc.text(t.footer, 48, 760, { width: 512, align: 'center' });
    doc.fillColor('#000000');
  }
}

function humanArea(area: string): string {
  return area
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ');
}

function humanPhase(phase: string, lang: PdfLanguage): string {
  const map: Record<PdfLanguage, Record<string, string>> = {
    en: { pre_tow: 'Pre-tow', post_tow: 'Post-tow', claim_review: 'Claim review' },
    es: {
      pre_tow: 'Antes del remolque',
      post_tow: 'Después del remolque',
      claim_review: 'Revisión de reclamo',
    },
  };
  return map[lang][phase] ?? phase;
}
