/**
 * Curated pickers for the intake form's vehicle block.
 *
 * Strategy: bundle a sensible default list rather than hit a remote VIN /
 * model database on every keystroke. The dispatcher's call is timed in
 * seconds, not minutes, so we want instant suggestions and zero network
 * dependency. Free-text entry is still allowed via the <datalist> pattern
 * on make / model and a "Custom…" sentinel on color, so anything missing
 * from this list can still be captured.
 *
 * Adding a make or model: drop it into the list below. Keep entries sorted
 * alphabetically inside each section so the dropdown reads naturally.
 */

export const STANDARD_COLORS = [
  'White',
  'Black',
  'Silver',
  'Gray',
  'Charcoal',
  'Red',
  'Maroon',
  'Burgundy',
  'Orange',
  'Yellow',
  'Gold',
  'Beige',
  'Tan',
  'Brown',
  'Bronze',
  'Green',
  'Blue',
  'Navy',
  'Purple',
  'Pearl',
] as const;

export type StandardColor = (typeof STANDARD_COLORS)[number];

/**
 * Top ~50 makes that account for the vast majority of US road traffic. Less
 * common marques (rare exotics, defunct OEMs) can still be typed in free-
 * form since the input is a real input, not a hard select.
 */
export const COMMON_MAKES = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Lucid',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mercury',
  'MINI',
  'Mitsubishi',
  'Nissan',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Ram',
  'Rivian',
  'Rolls-Royce',
  'Saab',
  'Saturn',
  'Scion',
  'Smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
] as const;

export type CommonMake = (typeof COMMON_MAKES)[number];

/**
 * Models keyed by make. Keep ~10–20 of each brand's bread-and-butter
 * nameplates. We intentionally include retired-but-still-on-the-road
 * models because they show up in tow calls (e.g. Pontiac G6, Hummer H2).
 * Anything not listed can still be typed in free-form.
 */
export const MODELS_BY_MAKE: Record<string, readonly string[]> = {
  Acura: ['ILX', 'Integra', 'MDX', 'RDX', 'RLX', 'RSX', 'TL', 'TLX', 'TSX', 'ZDX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', '4C', '8C'],
  'Aston Martin': ['DB11', 'DBS', 'DBX', 'Vanquish', 'Vantage'],
  Audi: [
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'e-tron',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'R8',
    'RS3',
    'RS5',
    'RS6',
    'RS7',
    'S3',
    'S4',
    'S5',
    'S6',
    'S7',
    'S8',
    'TT',
  ],
  Bentley: ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne'],
  BMW: [
    '1 Series',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'i3',
    'i4',
    'i5',
    'i7',
    'i8',
    'iX',
    'M2',
    'M3',
    'M4',
    'M5',
    'M8',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z4',
  ],
  Buick: [
    'Cascada',
    'Enclave',
    'Encore',
    'Encore GX',
    'Envision',
    'LaCrosse',
    'Lucerne',
    'Regal',
    'Verano',
  ],
  Cadillac: [
    'ATS',
    'CT4',
    'CT5',
    'CT6',
    'CTS',
    'DTS',
    'Escalade',
    'Escalade ESV',
    'LYRIQ',
    'SRX',
    'STS',
    'XT4',
    'XT5',
    'XT6',
    'XTS',
  ],
  Chevrolet: [
    'Aveo',
    'Blazer',
    'Bolt EUV',
    'Bolt EV',
    'Camaro',
    'Captiva',
    'Cavalier',
    'Cobalt',
    'Colorado',
    'Corvette',
    'Cruze',
    'Equinox',
    'Express',
    'HHR',
    'Impala',
    'Malibu',
    'Monte Carlo',
    'Sonic',
    'Spark',
    'Silverado 1500',
    'Silverado 2500',
    'Silverado 3500',
    'SS',
    'Suburban',
    'Tahoe',
    'Trailblazer',
    'Traverse',
    'Trax',
    'Volt',
  ],
  Chrysler: [
    '200',
    '300',
    'Aspen',
    'Crossfire',
    'Pacifica',
    'PT Cruiser',
    'Sebring',
    'Town & Country',
    'Voyager',
  ],
  Dodge: [
    'Avenger',
    'Caliber',
    'Caravan',
    'Challenger',
    'Charger',
    'Dart',
    'Durango',
    'Grand Caravan',
    'Hornet',
    'Journey',
    'Magnum',
    'Neon',
    'Nitro',
    'Ram',
    'Stratus',
    'Viper',
  ],
  Ferrari: ['296', '488', '812', 'F8', 'GTC4Lusso', 'Portofino', 'Purosangue', 'Roma', 'SF90'],
  Fiat: ['124 Spider', '500', '500e', '500L', '500X'],
  Ford: [
    'Bronco',
    'Bronco Sport',
    'C-Max',
    'Crown Victoria',
    'E-Series',
    'Ecosport',
    'Edge',
    'Escape',
    'Excursion',
    'Expedition',
    'Explorer',
    'F-150',
    'F-150 Lightning',
    'F-250',
    'F-350',
    'F-450',
    'Fiesta',
    'Five Hundred',
    'Flex',
    'Focus',
    'Freestyle',
    'Fusion',
    'GT',
    'Maverick',
    'Mustang',
    'Mustang Mach-E',
    'Ranger',
    'Taurus',
    'Transit',
    'Transit Connect',
  ],
  Genesis: ['Electrified G80', 'Electrified GV70', 'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  GMC: [
    'Acadia',
    'Canyon',
    'Envoy',
    'Hummer EV',
    'Jimmy',
    'Savana',
    'Sierra 1500',
    'Sierra 2500',
    'Sierra 3500',
    'Sonoma',
    'Terrain',
    'Yukon',
    'Yukon XL',
  ],
  Honda: [
    'Accord',
    'Civic',
    'Civic Type R',
    'Clarity',
    'CR-V',
    'CR-Z',
    'Crosstour',
    'Element',
    'Fit',
    'HR-V',
    'Insight',
    'Odyssey',
    'Passport',
    'Pilot',
    'Prelude',
    'Ridgeline',
    'S2000',
  ],
  Hummer: ['H1', 'H2', 'H3'],
  Hyundai: [
    'Accent',
    'Azera',
    'Elantra',
    'Equus',
    'Genesis',
    'Ioniq',
    'Ioniq 5',
    'Ioniq 6',
    'Kona',
    'Kona Electric',
    'Nexo',
    'Palisade',
    'Santa Cruz',
    'Santa Fe',
    'Sonata',
    'Tucson',
    'Veloster',
    'Venue',
    'Veracruz',
  ],
  Infiniti: [
    'EX35',
    'FX35',
    'FX50',
    'G35',
    'G37',
    'JX35',
    'M35',
    'M37',
    'M45',
    'Q50',
    'Q60',
    'Q70',
    'QX30',
    'QX50',
    'QX55',
    'QX60',
    'QX70',
    'QX80',
  ],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'S-Type', 'X-Type', 'XE', 'XF', 'XJ', 'XK'],
  Jeep: [
    'Cherokee',
    'Commander',
    'Compass',
    'Gladiator',
    'Grand Cherokee',
    'Grand Cherokee L',
    'Grand Wagoneer',
    'Liberty',
    'Patriot',
    'Renegade',
    'Wagoneer',
    'Wrangler',
    'Wrangler Unlimited',
  ],
  Kia: [
    'Cadenza',
    'Carnival',
    'EV6',
    'EV9',
    'Forte',
    'K5',
    'K900',
    'Niro',
    'Optima',
    'Rio',
    'Rondo',
    'Sedona',
    'Seltos',
    'Sorento',
    'Soul',
    'Spectra',
    'Sportage',
    'Stinger',
    'Telluride',
  ],
  Lamborghini: ['Aventador', 'Gallardo', 'Huracán', 'Revuelto', 'Urus'],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'LR2',
    'LR3',
    'LR4',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport',
    'Range Rover Velar',
  ],
  Lexus: [
    'CT200h',
    'ES',
    'GS',
    'GX',
    'IS',
    'LC',
    'LFA',
    'LS',
    'LX',
    'NX',
    'RC',
    'RX',
    'SC',
    'TX',
    'UX',
  ],
  Lincoln: [
    'Aviator',
    'Continental',
    'Corsair',
    'MKC',
    'MKS',
    'MKT',
    'MKX',
    'MKZ',
    'Nautilus',
    'Navigator',
    'Town Car',
    'Zephyr',
  ],
  Lotus: ['Elise', 'Emira', 'Eletre', 'Evora', 'Exige'],
  Lucid: ['Air', 'Gravity'],
  Maserati: ['Ghibli', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  Mazda: [
    'Mazda2',
    'Mazda3',
    'Mazda5',
    'Mazda6',
    'CX-3',
    'CX-30',
    'CX-5',
    'CX-50',
    'CX-7',
    'CX-9',
    'CX-90',
    'MX-30',
    'MX-5 Miata',
    'Tribute',
    'RX-8',
  ],
  McLaren: [
    '540C',
    '570S',
    '600LT',
    '650S',
    '675LT',
    '720S',
    '750S',
    'Artura',
    'GT',
    'P1',
    'Senna',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'AMG GT',
    'B-Class',
    'C-Class',
    'CL-Class',
    'CLA',
    'CLK',
    'CLS',
    'E-Class',
    'EQE',
    'EQS',
    'G-Class',
    'GL-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLK',
    'GLS',
    'M-Class',
    'Metris',
    'R-Class',
    'S-Class',
    'SL',
    'SLC',
    'SLK',
    'SLS',
    'Sprinter',
  ],
  Mercury: ['Grand Marquis', 'Mariner', 'Milan', 'Montego', 'Mountaineer', 'Sable'],
  MINI: ['Clubman', 'Convertible', 'Cooper', 'Cooper Countryman', 'Cooper Paceman', 'Cooper SE'],
  Mitsubishi: [
    'Eclipse',
    'Eclipse Cross',
    'Endeavor',
    'Galant',
    'i-MiEV',
    'Lancer',
    'Mirage',
    'Outlander',
    'Outlander Sport',
    'Raider',
  ],
  Nissan: [
    '350Z',
    '370Z',
    'Altima',
    'Ariya',
    'Armada',
    'Cube',
    'Frontier',
    'GT-R',
    'Juke',
    'Kicks',
    'Leaf',
    'Maxima',
    'Murano',
    'NV200',
    'Pathfinder',
    'Quest',
    'Rogue',
    'Rogue Sport',
    'Sentra',
    'Titan',
    'Versa',
    'Xterra',
    'Z',
  ],
  Polestar: ['1', '2', '3', '4'],
  Pontiac: [
    'Aztek',
    'Bonneville',
    'G3',
    'G5',
    'G6',
    'G8',
    'GTO',
    'Grand Am',
    'Grand Prix',
    'Solstice',
    'Sunfire',
    'Torrent',
    'Vibe',
  ],
  Porsche: [
    '718 Boxster',
    '718 Cayman',
    '911',
    'Boxster',
    'Cayenne',
    'Cayman',
    'Macan',
    'Panamera',
    'Taycan',
  ],
  Ram: ['1500', '2500', '3500', '4500', '5500', 'ProMaster', 'ProMaster City'],
  Rivian: ['R1S', 'R1T'],
  'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Spectre', 'Wraith'],
  Saab: ['9-3', '9-4X', '9-5', '9-7X'],
  Saturn: ['Astra', 'Aura', 'Ion', 'Outlook', 'Sky', 'Vue'],
  Scion: ['FR-S', 'iA', 'iM', 'iQ', 'tC', 'xA', 'xB', 'xD'],
  Smart: ['Fortwo'],
  Subaru: [
    'Ascent',
    'Baja',
    'BRZ',
    'Crosstrek',
    'Forester',
    'Impreza',
    'Legacy',
    'Outback',
    'Solterra',
    'Tribeca',
    'WRX',
    'XV Crosstrek',
  ],
  Suzuki: ['Aerio', 'Equator', 'Forenza', 'Grand Vitara', 'Kizashi', 'Reno', 'SX4', 'XL-7'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster', 'Semi'],
  Toyota: [
    '4Runner',
    '86',
    'Avalon',
    'Avanza',
    'C-HR',
    'Camry',
    'Celica',
    'Corolla',
    'Corolla Cross',
    'Corolla Hatchback',
    'Crown',
    'FJ Cruiser',
    'GR86',
    'GR Corolla',
    'GR Supra',
    'Highlander',
    'Land Cruiser',
    'Matrix',
    'Mirai',
    'Prius',
    'Prius Prime',
    'RAV4',
    'RAV4 Prime',
    'Sequoia',
    'Sienna',
    'Solara',
    'Supra',
    'Tacoma',
    'Tundra',
    'Venza',
    'Yaris',
  ],
  Volkswagen: [
    'Arteon',
    'Atlas',
    'Atlas Cross Sport',
    'Beetle',
    'CC',
    'Eos',
    'Golf',
    'GTI',
    'ID.4',
    'ID. Buzz',
    'Jetta',
    'Passat',
    'Phaeton',
    'R32',
    'Rabbit',
    'Routan',
    'Taos',
    'Tiguan',
    'Touareg',
  ],
  Volvo: [
    'C30',
    'C40',
    'C70',
    'EX30',
    'EX90',
    'S40',
    'S60',
    'S80',
    'S90',
    'V40',
    'V50',
    'V60',
    'V70',
    'V90',
    'XC40',
    'XC60',
    'XC70',
    'XC90',
  ],
};

export function modelsForMake(make: string): readonly string[] {
  const trimmed = make.trim();
  if (!trimmed) return [];
  // Direct hit first; fall back to case-insensitive lookup so a dispatcher
  // typing "honda" still gets the Honda model list.
  if (trimmed in MODELS_BY_MAKE) return MODELS_BY_MAKE[trimmed] ?? [];
  const lower = trimmed.toLowerCase();
  for (const key of Object.keys(MODELS_BY_MAKE)) {
    if (key.toLowerCase() === lower) return MODELS_BY_MAKE[key] ?? [];
  }
  return [];
}
